version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  patient-app:
    image: node:4-onbuild
    container_name: patient-app
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
